const foodData = [
  { id: 1, name: "Margherita Pizza", price: 399, image: "/assets/img/Margherita Pizza.jpg" },
  { id: 2, name: "Veg Burger", price: 129, image: "/assets/img/Burgur.jpg" },
  { id: 3, name: "Pasta Alfredo", price: 149, image: "/assets/img/Pasta Alfredo.jpg" },
  { id: 4, name: "French Fries", price: 109, image: "/assets/img/French Fries.jpg" },
  { id: 5, name: "Grilled Sandwich", price: 229, image: "/assets/img/Grilled Sandwich.jpg" },
  { id: 6, name: "Chocolate Shake", price: 120, image: "/assets/img/Chocolate Shake.jpg" },
  { id: 7, name: "Paneer Tikka", price: 380, image: "/assets/img/Paneer Tikka.jpg" },
  { id: 8, name: "Mexican Wrap", price: 300, image: "/assets/img/Mexican Wrap.jpg" },
  { id: 9, name: "Cheese Garlic Bread", price: 190, image: "/assets/img/Cheese Garlic Bread.webp" },
  { id: 10, name: "Spring Rolls", price: 230, image: "/assets/img/Spring Rolls.jpg" },
  { id: 11, name: "Cold Coffee", price: 210, image: "/assets/img/Cold Coffee.jpg" },
  { id: 12, name: "Fruit Salad", price: 180, image: "/assets/img/Fruit Salad.jpg" },
  { id: 13, name: "Paneer Butter Masala", price: 259, image: "/assets/img/Paneer Butter Masala.webp" },
  { id: 14, name: "Veg Momos", price: 89, image: "/assets/img/Veg Momos.jpg" },
  { id: 15, name: "Hakka Noodles", price: 150, image: "/assets/img/Hakka Noodles.jpg" },
  { id: 16, name: "Oreo Shake", price: 180, image: "/assets/img/Oreo Shake.jpg" },
  { id: 17, name: "Chole Bhature", price: 210, image: "/assets/img/Chole Bhature.jpg" },
  { id: 18, name: "Masala Dosa", price: 190, image: "/assets/img/Masala Dosa.jpg" },
  { id: 19, name: "Veg Fried Rice", price: 270, image: "/assets/img/Veg Fried Rice.jpg" },
  { id: 20, name: "Ice Cream Sundae", price: 210, image: "/assets/img/Ice Cream Sundae.jpg" },
  { id: 21, name: "Chicken Biryani", price: 280, image: "/assets/img/Chicken Biryani.jpg" },
  { id: 22, name: "Veg Thali", price: 210, image: "/assets/img/Veg Thali.jpg" },
  { id: 23, name: "Chicken Roll", price: 160, image: "/assets/img/Chicken Roll.jpg" },
  { id: 24, name: "Paneer Wrap", price: 199, image: "/assets/img/Paneer Wrap.jpg" },
  { id: 25, name: "Veg Pizza Slice", price: 90, image: "/assets/img/Veg Pizza Slice.jpg" },
  { id: 26, name: "Mango Lassi", price: 80, image: "/assets/img/Mango Lassi.jpg" },
  { id: 27, name: "Chocolate Donut", price: 90, image: "/assets/img/Chocolate Donut.jpg" },
  { id: 28, name: "Rasmalai", price: 110, image: "/assets/img/Rasmalai.jpeg" },
  { id: 29, name: "Kaju Katli", price: 330, image: "/assets/img/Kaju Katli.jpg" },
  { id: 30, name: "Jalebi", price: 70, image: "/assets/img/Jalebi.jpg" },
  { id: 31, name: "Brownie", price: 270, image: "/assets/img/Brownie.jpg" },
  { id: 32, name: "Strawberry Cupcake", price: 99, image: "/assets/img/Strawberry Cupcake.jpg" },
  { id: 33, name: "Vanilla Pudding", price: 99, image: "/assets/img/Vanilla Pudding.jpg" },
  { id: 34, name: "Fruit Custard", price: 109, image: "/assets/img/Fruit Custard.jpg" },
  { id: 35, name: "Mango Kulfi", price: 120, image: "/assets/img/Mango Kulfi.jpg" },
  { id: 36, name: "Black Forest Pastry", price: 129, image: "/assets/img/Black Forest Pastry.jpg" },
  { id: 37, name: "Milk Cake", price: 99, image: "/assets/img/Milk Cake.jpg" },
  { id: 38, name: "Caramel Custard", price: 110, image: "/assets/img/Caramel Custurd.jpg" },
  { id: 39, name: "Rasgulla", price: 99, image: "/assets/img/Rasgulla.jpg" },
  { id: 40, name: "Cheesecake", price: 179, image: "/assets/img/Cheesecake.jpg" },
  { id: 41, name: "Muffin", price: 99, image: "/assets/img/Muffin.jpg" },
  { id: 42, name: "Apple Pie", price: 149, image: "/assets/img/Apple Pie.jpg" },
  { id: 43, name: "Tiramisu", price: 199, image: "/assets/img/Tiramisu.jpg" },
  { id: 44, name: "Shrikhand", price: 120, image: "/assets/img/Shrikhand.jpg" },
  { id: 45, name: "Basundi", price: 150, image: "/assets/img/Basundi.webp" },
  { id: 46, name: "Malpua", price: 160, image: "/assets/img/Malpua.jpg" },
  { id: 47, name: "Butterscotch Mousse", price: 159, image: "/assets/img/Butterscotch Mousse.jpg" },
  { id: 48, name: "Gulab Jamun", price: 90, image: "/assets/img/Gulab Jamun.webp" },
  { id: 49, name: "Paneer Pizza", price: 560, image: "/assets/img//paneer pizza.jpg" },
  { id: 50, name: "Doublecheese Pizza", price: 90, image: "/assets/img/doublecheese pizza.jpeg" },
  { id: 51, name: "Cheese Volcano Pizza", price: 90, image: "/assets/img/cheese valcano pizza.jpg" },
  { id: 52, name: "Pepperoni Pizza", price: 90, image: "/assets/img/Prproni.jpg" },
  { id: 53, name: "Chicken Tikka Pizza", price: 90, image: "/assets/img/chicken tikka pizza.png" },
  { id: 54, name: "Flatbread Pizza", price: 90, image: "/assets/img/Flatbreads pizza.jpg" },
  { id: 55, name: "Virgin Mojito Mocktail", price: 90, image: "/assets/img/Virgin Mojito Mocktail.jpg" },
  { id: 56, name: "Pina Colada Mocktail", price: 90, image: "/assets/img/Pina Colada Mocktail.jpg" },
  { id: 57, name: "Shirley Temple Mocktail", price: 90, image: "/assets/img/Shirley Temple Mocktail.jpg" },
  { id: 58, name: "Virgin Mary Mocktail", price: 90, image: "/assets/img//Virgin Mary Mocktail.jpg" },
  { id: 59, name: "Fruity Sangria Mocktail", price: 90, image: "/assets/img/Fruity Sangria Mocktail.webp" },
  { id: 60, name: "Arnold Palmer Mocktail", price: 90, image: "/assets/img/Arnold Palmer MOcktail.avif" },
  { id: 61, name: "Green Tea", price: 90, image: "/assets/img/Green Tea.avif" },
  { id: 62, name: "Milk Tea", price: 90, image: "/assets/img/Milk Tea.jpg" },
  { id: 63, name: "Coca-Cola", price: 90, image: "/assets/img/coca-cola.jpg" },
  { id: 64, name: "Pepsi", price: 90, image: "/assets/img/Pepsi.jpg" },
  { id: 65, name: "Fanta", price: 90, image: "/assets/img/fanta.jpg" },
  { id: 66, name: "Non-Veg Thali", price: 90, image: "/assets/img/non veg thali.webp" },
  { id: 67, name: "Chicken Burger", price: 90, image: "/assets/img/chick burger.jpg" },
  { id: 68, name: "Cheese Burger", price: 90, image: "/assets/img/chese burger.jpg" },
  { id: 69, name: "BBQ Burger", price: 90, image: "/assets/img/BBQ Burger.jpg" },
  { id: 70, name: "Chili Burger", price: 90, image: "/assets/img/Chili Burger.jpg" },
  { id: 71, name: "Hawaiian Burger", price: 90, image: "/assets/img/Hawaiian Burger.jpg" },
  { id: 72, name: "Peanut Butter & Jelly Sandwich", price: 90, image: "/assets/img/Peanut Butter & Jelly Sandwich.jpg" },
  { id: 73, name: "Club Sandwich", price: 90, image: "/assets/img/Club Sandwich.jpg" },
  { id: 74, name: "Cuban sandwich", price: 90, image: "/assets/img/cuban sandwich.jpg" },
  { id: 75, name: "Banh Mi sandwich", price: 90, image: "/assets/img/Banh Mi sandwich.jpg" },
  { id: 76, name: "Tandoori Chicken Grilled Sandwich", price: 90, image: "/assets/img/Tandoori Chicken Sandwich.jpeg" },
  { id: 77, name: "Croque Monsieur sandwich", price: 90, image: "/assets/img/Croque Monsieur sandwich.jpg" },
  { id: 78, name: "Fettuccine Pasta", price: 90, image: "/assets/img/Fettuccine.webp" },
  { id: 79, name: "Linguine Pasta", price: 90, image: "/assets/img/Linguine.webp" },
  { id: 80, name: "Macaroni pasta", price: 90, image: "/assets/img/Macaroni pasta.jpg" },
  { id: 81, name: "Rigatoni pasta", price: 90, image: "/assets/img/Rigatoni pasta.jpg" },
  { id: 82, name: "Fusilli pasta", price: 90, image: "/assets/img/Fusilli pasta.jpg" },
  { id: 83, name: "Tortellini pasta", price: 90, image: "/assets/img/Tortellini pasta.avif" },
  { id: 84, name: "Lasagna pasta", price: 90, image: "/assets/img/Lasagna pasta.jpg" },
  { id: 85, name: "Udon Noodels", price: 90, image: "/assets/img/Udon Noodels.jpg" },
  { id: 86, name: "Chow Mein Noodles", price: 90, image: "/assets/img/Chow Mein.avif" },
  { id: 87, name: "Hokkien Noodles", price: 90, image: "/assets/img/Hokkien Noodles.jpeg" },
  { id: 88, name: "Yaki Chicken Noodles", price: 90, image: "/assets/img/Yaki chicken Noodels.jpeg" },
  { id: 89, name: "Gobi Manchurian", price: 90, image: "/assets/img/Gobi Manchurian.jpg" },
  { id: 90, name: "Dahi puri", price: 90, image: "/assets/img/Dahi puri.jpeg" },
  { id: 91, name: "Seekh Kebabs", price: 90, image: "/assets/img/Seekh Kebabs.jpg" },
  { id: 93, name: "Stuffed Mushrooms", price: 90, image: "/assets/img/Stuffed Mushrooms.jpg" },
  { id: 94, name: "Roasted Tomato Bruschetta", price: 90, image: "/assets/img/Roasted Tomato Bruschetta.jpg" },
  { id: 95, name: "Gravy Manchurian", price: 90, image: "/assets/img/Gravy Manchurian.avif" },
  { id: 96, name: "Samosa", price: 90, image: "/assets/img/Samosa.jpg" },
  { id: 97, name: "Shev Puri", price: 90, image: "/assets/img//Shev Puri.jpg" },
  { id: 98, name: "Masala papad", price: 90, image: "/assets/img/Masala papad.webp" },
  { id: 99, name: "Veg Biryani", price: 90, image: "/assets/img/Veg Biryani.jpg" },
  { id: 100, name: "French Onion Garlic Bread", price: 90, image: "/assets/img/French Onion Garlic Bread.jpg" },
  { id: 101, name: "Cream Cheese Baguette Garlic Bread", price: 90, image: "/assets/img/Cream Cheese Baguette Bread.jpg" },
  { id: 102, name: "Sourdough Garlic Bread", price: 90, image: "/assets/img/Sourdough Garlic Bread.jpg" },
  { id: 103, name: "Chicken Caesar salad", price: 90, image: "/assets/img/Chicken Caesar salad.jpeg" },
  { id: 104, name: "Veg Caesar salad", price: 90, image: "/assets/img/Veg Caesar salad..jpeg" },
  { id: 105, name: "Cobb salad", price: 90, image: "/assets/img/Cobb salad.jpg" },
  { id: 106, name: "Coleslaw Salad", price: 90, image: "/assets/img/Coleslaw Salad.jpeg" },
  { id: 107, name: "Tabbouleh Salad", price: 90, image: "/assets/img/Tabbouleh Salad.jpg" },
  { id: 108, name: "Waldorf salad", price: 90, image: "/assets/img/Waldorf salad.jpeg" },
  { id: 109, name: "Kitkat Milkshake", price: 90, image: "/assets/img/Kitkat Milkshake.avif" },
  { id: 110, name: "Butterscotch Milkshake", price: 90, image: "/assets/img/Butterscotch Milkshake.jpeg" },
  { id: 111, name: "Salted Caramel milkshake", price: 90, image: "/assets/img/Salted Caramel milkshake.jpeg" },
  { id: 112, name: "Mint Chocolate Chip Milkshake", price: 90, image: "/assets/img/Mint Chocolate Chip Milkshake.jpg" },
  { id: 113, name: "Butter Chicken Bonanza", price: 349, image: "/assets/img/chick.jpg" },
  { id: 114, name: "Chocolate Fudge Cake", price: 249, image: "/assets/img/fudge cake.webp" },


];

export default foodData;
